### ISSUE TITLE
MAUI builds fail in Azure DevOps pipeline following update to latest MSAL version

### ISSUE THREAD

**Issue by mtanml** [Azure-Samples/ms-identity-ciam-dotnet-tutorial#139]
We're getting build errors in our Azure DevOps pipeline since updating from 4.66.2 to 4.68:

_Platforms/iOS/AppDelegate.cs(29,23): error CS0103: The name 'AuthenticationContinuationHelper' does not exist in the current context_ 

The app runs fine in Visual Studio.
